RMSRCBUILD-275 Inline MSBuildExtensionPack tasks to support building using dotnet
re-motion/SharedSource-Build pull request #69
Opened 2022-05-18 07:15 UTC by a-ctor

https://re-motion.atlassian.net/browse/RMSRCBUILD-275

2022-05-20 10:42 UTC, MichaelKetting requested changes

2022-05-20 12:02 UTC, a-ctor commented on BuildScript/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
The binding redirect was created by installing the Nuget package so I assumed it to be necessary

2022-05-20 12:04 UTC, MichaelKetting commented on BuildScript/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
yeah, that's a nuget default.  the question is, does the whole thing work inside the nuget package? (i.e. without the app.config?)

2022-05-21 07:45 UTC, a-ctor commented on BuildScript/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
I looked and they were not packaged, so I removed them from the package

2022-05-21 13:35 UTC, MichaelKetting approved these changes

2022-05-22 09:42 UTC, merged