Feature/rmsrcb UI ld 108 performing a release from a release branch should not merge back into develop
re-motion/SharedSource-Build pull request #74
Opened 2022-06-21 08:44 UTC by Frazerus

2022-06-21 10:46 UTC, MichaelKetting requested changes

2022-06-21 10:46 UTC, MichaelKetting commented on ReleaseProcessAutomation.Tests/IntegrationTests/ReleaseFromDevelopTests.cs
> +                    ";
Is this whitespace change correct? it's different from the rest.

2022-06-22 06:16 UTC, Frazerus commented on ReleaseProcessAutomation.Tests/Steps/Continues/ContinueReleaseOnMasterStepTests.cs
> +  public void CreateTagAndMerge_DoesNotMergeIntoDevelop_ContinuesToNextStep ()
`Execute` is used when the method to test is the Execute method
`CreateTagAndMerge` is used when the test should just go through Execute cleanly and test behaviour of the `CreateTagAndMerge` method

2022-06-22 07:26 UTC, MichaelKetting approved these changes

2022-06-22 09:27 UTC, merged