Feature/RMSRCBUILD-281 check test names
re-motion/SharedSource-Build pull request #98
Opened 2022-08-19 08:42 UTC by Frazerus

https://re-motion.atlassian.net/browse/RMSRCBUILD-281

2022-08-22 09:16 UTC, MichaelKetting reviewed
Got some recommendations/improvements. I tried to mark everyting I found. And I tried to be thorough to give you the most input on reasoning/best practices, etc.

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/MsBuildIntegrationTests.cs
> +  public void ExecuteNormalReleaseVersion_ShouldCallMsBuild ()
```suggestion
  public void ExecuteNormalReleaseVersion_CallsMsBuild ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void ReleaseVersionAndSquashUnreleased_WithUnrelatedVersion_ShouldNotSquashUnrelatedVersions ()
```suggestion
  public void ReleaseVersionAndSquashUnreleased_WithUnrelatedVersion_DoesNotSquashUnrelatedVersions ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void ReleaseVersionAndSquashUnreleased_WithOpenIssueOnBetweenVersion_ShouldSquashUnreleasedAndMoveIssues ()
```suggestion
  public void ReleaseVersionAndSquashUnreleased_WithOpenIssueOnBetweenVersion_SquashesUnreleasedVersionsAndMovesIssues ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void ReleaseVersionAndSquashUnreleased_WithOneVersionBetweenAlreadyReleased_ShouldThrow ()
```suggestion
  public void ReleaseVersionAndSquashUnreleased_WithUnreleasedVersionBetweenAlreadyReleasedVersions_ThrowsException ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void DeleteVersion_WithoutExistentVersion_DoesThrow ()
```suggestion
  public void DeleteVersion_WithoutExistingVersion_ThrowsException ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void DeleteVersion_WithExistentVersion_DoesNotThrow ()
```suggestion
  public void DeleteVersion_WithExistingVersion_DeletesVersion ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void CreateVersion_WithAlreadyExistentVersion_ThrowsException ()
```suggestion
  public void CreateVersion_WithAlreadyExistingVersion_ThrowsException ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void FindUnreleasedVersion_WithNonExistentPatter_ReturnsEmpty ()
```suggestion
  public void FindUnreleasedVersion_WithNoVersionMatchingThePattern_ReturnsEmpty ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +  public void FindAllVersionsWithVersionNumber_With3CorrectVersions_FindsProperVersions ()
```suggestion
  public void FindAllVersionsWithVersionNumber_WithThreeCorrectVersions_FindsProperVersions ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +  public void ReleaseVersionAndMoveIssues_NoIssuesToMove_DoesNotThrow ()
```suggestion
  public void ReleaseVersionAndMoveIssues_NoIssuesToMove_PerformsReleaseWithoutUpdatingAnyIssues ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/GitBranchOperationTests.cs
> +  public void EnsureBranchUpToDate_WithCurrentBehind_DoesThrow ()
```suggestion
  public void EnsureBranchUpToDate_WithCurrentBehind_ThrowsException ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
> +  public void MergeBranchWithoutCommit_WithConflictsAndNoAutomaticResolution_ShouldThrow ()
```suggestion
  public void MergeBranchWithoutCommit_WithConflictsAndNoAutomaticResolution_ThrowsException ()
```

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
> +  public void GetAncestors_WithTwoExpectedAncestors_ReturnsBothNameMatched ()
`ReturnsNameMatched` is there a better way to say this, e.g. `ReturnsMatchingName` or `ReturnsNameBasedOnAncestor` etc?

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
> +  public void GetAncestors_ReleaseOnSameCommitAsDevelop_ReturnsNameMatched ()
see GetAncestors_WithTwoExpectedAncestors_ReturnsBothNameMatched

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
> +  public void GetAncestors_SeveralBranchesFromMaster_ReturnsNameMatched ()
see GetAncestors_WithTwoExpectedAncestors_ReturnsBothNameMatched

2022-08-22 09:16 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/AncestorFinderTests.cs
> +  public void GetAncestor_OneFound_ReturnsSingleFound ()
```suggestion
  public void GetAncestor_WithOneAncestor_ReturnsFoundAncestor ()
```

2022-08-22 10:18 UTC, Frazerus commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
> +  public void InternalSetup ()
Does this setup override the setup in the base class? That was the main thought for using non standard setup naming for this. But I guess we're using Setup so often it is already bound to have the same name as the Setup in the base class.

2022-08-22 10:27 UTC, Frazerus commented on ReleaseProcessAutomation.UnitTests/Steps/Releases/ReleaseNonPreReleaseFromDevelopTests.cs
> +  public void Execute_WithWorkingDirectoryNotCleanWithoutConfirmation_ThrowsException ()
Does `Execute_WithWorkingDirectoryNotCleanAndNoConfirmationToContinue_ThrowsException` make more sense? I think this should make it obvious what is happening.

2022-08-22 10:57 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
> +  public void InternalSetup ()
ah, I see. I didn't check the features of nunit, but historically, we simply did method overrides => setup is virtual on the basetype and has the setup-attribute applied. derived testfixture simply does a methode override, no attribute needed.

2022-08-22 10:58 UTC, MichaelKetting commented on ReleaseProcessAutomation.UnitTests/Steps/Releases/ReleaseNonPreReleaseFromDevelopTests.cs
> +  public void Execute_WithWorkingDirectoryNotCleanWithoutConfirmation_ThrowsException ()
yeah. stylistic: I usually insert an underscore between the parts, i.e. before the `And`, too.

2022-08-22 11:53 UTC, MichaelKetting requested changes

2022-08-22 11:53 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
>    {
as discussed, base call

2022-08-22 11:53 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Git/CommandLineGitClientTests.cs
> +  public void DoesRemoteBranchExists_WithoutExistentBranch_ReturnsFalse ()
```suggestion
  public void DoesRemoteBranchExists_WithoutExistingBranch_ReturnsFalse ()
```

2022-08-22 11:53 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +  public void FindIssuesWithOnlyExactFixVersion_WithSeveralWrongIssues_ReturnsSingleCorrectIssue ()
`ReturnsSingleCorrectIssue ` => the number of correct issues isn't really important, is it? i.e. we don't know or expect there to be a single correct issue and it's also not derived from the other parts of the test name. Do you mean `ReturnsOnlyCorrectIssues`? 

also `CorrectIssue` and `WrongIssue` =>please qualify, i.e. is it issues that have the correct/incorrect version? And what does this mean?

You should be able to deduce the basic behavior of the code just by reading the names (and knowing a bit about the indended behavior of the tool). for me, the current name is a bit too far out there, so I can only inject my own interpretation into the test name, which isn't a good thing.

2022-08-22 11:53 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void DeleteVersion_WithExistentVersion_DeletesVersion ()
```suggestion
  public void DeleteVersion_WithExistingVersion_DeletesVersion ()
```

2022-08-22 11:53 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void DeleteVersion_WithoutExistentVersion_ThrowsException ()
```suggestion
  public void DeleteVersion_WithoutExistingVersion_ThrowsException ()
```

2022-08-22 11:53 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraProjectVersionServiceTest.cs
> +  public void RepairVersionPosition_WithNetVersions_SortsVersions()
`Net`? what does that mean?

2022-08-22 11:53 UTC, MichaelKetting commented on ReleaseProcessAutomation.UnitTests/Steps/InitialBranching/BranchFromReleaseForContinueVersionStepTests.cs
> +  public void Execute_WithInvalidAncestor_DoesThrow ()
```suggestion
  public void Execute_WithInvalidAncestor_ThrowsException ()
```

2022-08-23 10:44 UTC, MichaelKetting approved these changes
The rename of the base classes can (should?) be a separate ticket.

2022-08-23 10:44 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
>      var testCredentials = JiraTestUtility.GetLocallySavedCredentials();
Inconsistent whitespace indent

2022-08-23 10:44 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/IntegrationTestSetup.cs
> +  public virtual void Setup ()
Class name: base types should be abstract and end in `Base`. Here, it would be IntegrationTestBase

2022-08-23 10:44 UTC, MichaelKetting commented on ReleaseProcessAutomation.IntegrationTests/GitBackedTests.cs
>    private string _remotePath;
Class name: base types should be abstract and end in `Base`. Here, it would be GitBackedTestBase

2022-08-24 06:36 UTC, merged

2022-08-24 06:42 UTC, Frazerus commented
Created extra ticket for renaming base names.